defaults:
  - _self_
  - task: kitchen-mixed-v0

# General
pipeline_name: cd_dql_d4rl_${env_name}
device: cuda:0

# Method
method: dql
mode: train
seed: 0

# Environment
env_name: kitchen
normalize_reward: True
discount: 0.99

max_episode_steps: ${max_episode_steps_per_env.${env_name}}
max_episode_steps_per_env:
  kitchen: 280
  mujoco: 1000
  antmaze: 1000

# Actor
solver: ddim
predict_noise: True
diffusion_steps: 10
sampling_steps: 5
ema_rate: 0.995
actor_learning_rate: 0.0003

# Critic
hidden_dim: 256
critic_learning_rate: 0.0003

# Contraction
lambda_contr: 0.1
loss_type: "all" # or "eigen_max" or "eigen_avg" or "all"

loss_weights:
  jacobian: 0.0
  eigen_max: 0.0
  eigen_avg: 0.0

num_power_iters: 5

# Wandb
wandb_mode: online
project: contractive_diffuser
group: ${method}_${env_name}
exp_name: cd_dql
log_dir: logs

# Training
gradient_steps: 100000
batch_size: 256
ema_update_interval: 5
log_interval: 200
save_interval: 50000
eval_interval: 10000

# Inference
ckpt: latest
num_envs: 5
num_episodes: 10
num_candidates: 100
temperature: 0.5
use_ema: True

# hydra
hydra:
  job:
    chdir: false
  run:
    dir: ${log_dir}/${pipeline_name}/${task.env_name}/hydra/${seed}
  output_subdir: null

